import { Project } from "./types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "1",
    title: "VectorMind",
    tagline: "AI-powered code review that understands context",
    description:
      "VectorMind uses RAG with VectorAI DB to deeply understand your codebase. It provides contextual code reviews by retrieving relevant patterns, past decisions, and architectural conventions — going far beyond simple linting.",
    image: "/projects/vectormind.png",
  },
  {
    id: "2",
    title: "DataWeaver",
    tagline: "Natural language to SQL, powered by semantic search",
    description:
      "DataWeaver lets non-technical users query complex databases using plain English. It leverages vector embeddings stored in Actian VectorAI DB to match user intent with the correct schema and query patterns.",
    image: "/projects/dataweaver.png",
  },
  {
    id: "3",
    title: "MemoryBot",
    tagline: "A chatbot that never forgets your preferences",
    description:
      "MemoryBot builds a persistent semantic memory layer on top of VectorAI DB. Every conversation enriches its understanding of user preferences, enabling truly personalized interactions over time.",
    image: "/projects/memorybot.png",
  },
  {
    id: "4",
    title: "DocuSense",
    tagline: "Instant answers from your entire knowledge base",
    description:
      "DocuSense ingests documentation, wikis, and PDFs into VectorAI DB, then provides precise answers with source citations. It reduces onboarding time by 80% for new team members.",
    image: "/projects/docusense.png",
  },
  {
    id: "5",
    title: "AgentSwarm",
    tagline: "Coordinated multi-agent task execution",
    description:
      "AgentSwarm orchestrates multiple specialized AI agents that share a common vector memory in Actian VectorAI DB. Agents collaborate on complex tasks by storing and retrieving shared context seamlessly.",
    image: "/projects/agentswarm.png",
  },
  {
    id: "6",
    title: "PixelScout",
    tagline: "Visual similarity search for design systems",
    description:
      "PixelScout indexes UI components as vector embeddings in VectorAI DB, enabling designers to find visually similar components across projects. It prevents design drift and promotes consistency.",
    image: "/projects/pixelscout.png",
  },
  {
    id: "7",
    title: "ThreatRadar",
    tagline: "Real-time anomaly detection with semantic context",
    description:
      "ThreatRadar embeds security events into VectorAI DB and uses semantic similarity to detect novel attack patterns. It catches zero-day threats that rule-based systems miss entirely.",
    image: "/projects/threatradar.png",
  },
  {
    id: "8",
    title: "SynthTutor",
    tagline: "Adaptive learning paths generated by AI",
    description:
      "SynthTutor creates personalized curricula by mapping learner progress against a knowledge graph stored in VectorAI DB. It identifies gaps and generates targeted exercises in real time.",
    image: "/projects/synthtutor.png",
  },
];
